version: "3"

services:
  app:
    build: .
    environment:
      MONGO_URL: "mongodb://root:example@mongo:27017/test"
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    command: yarn start:dev
    volumes:
      - .:/home/nodejs/app
      - /home/nodejs/app/node_modules
      - node:/home/nodejs/
    
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nestjs
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  mongodata: {}
  node: {}